In [2]:
import os
import sys
from pathlib import Path
import pandas as pd
import re
import unicodedata
from datasets import load_from_disk
from config import CONFIG

sys.path.append(os.path.abspath(".."))

In [11]:
path = Path('../data/datasets/corpus-webis-authorship/koppel/')

In [22]:
# df = pd.DataFrame(columns=['author', 'text'])


data = []
for author in path.iterdir():
    if author.is_dir():
        for file in author.iterdir():
            if file.is_file() and file.suffix == '.txt':
                with open(file, 'r', encoding='utf-8', errors='replace') as f:
                    content = f.read()
                    content = unicodedata.normalize("NFKC", content)
                    content = re.sub(r"[^\x00-\x7F]+", " ", content)
                    content = re.sub(r"\s+", " ", content)
                    content = content.strip().lower()
                    data.append({'author': author.name, 'text': content, 'n_chars': len(content)})
df = pd.DataFrame(data)
display(df)

,author,text,n_chars
0,Henry_David_Thoreau,a week on the concord and merrimack rivers. [p...,643693
1,Henry_David_Thoreau,"walden, and on the duty of civil disobedience ...",632112
2,Oscar_Wilde,a woman of no importance a play by oscar wilde...,124703
3,Oscar_Wilde,an ideal husband a play by oscar wilde * * * *...,173151
4,Nathaniel_Hawtorne,introductory note. the house of the seven gabl...,610975
5,Nathaniel_Hawtorne,preface a preface generally begins with a trui...,527969
6,James_Fenimore_Cooper,"chapter i ""mine ear is open, and my heart prep...",840675
7,James_Fenimore_Cooper,"james fenimore cooper ""i believe i could write...",856429
8,James_Fenimore_Cooper,"the water-witch; or, the skimmer of the seas. ...",887927
9,Charlotte_Bronte,preface. this little book was written before e...,495655
10,Charlotte_Bronte,"preface a preface to the first edition of ""jan...",1019915
11,Bernard_Shaw,"misalliance _johnny tarleton, an ordinary youn...",175535
12,Bernard_Shaw,preface to pygmalion. a professor of phonetics...,186934
13,Bernard_Shaw,preface to getting married the revolt against ...,326083
14,Ralph_Waldo_Emerson,the conduct of life. by r. w. emerson. boston:...,377181
15,Ralph_Waldo_Emerson,english traits. by ralph waldo emerson. new an...,374245
16,Anne_Bronte,introduction anne bront serves a twofold purpo...,920969
17,Anne_Bronte,chapter i the parsonage all true histories con...,370367
18,Herman_Melville,etymology. (supplied by a late consumptive ush...,1205794
19,Herman_Melville,i. how wellingborough redburn's taste for the ...,652705

In [3]:
ds_koppel = load_from_disk(os.path.join(os.path.abspath(".."), CONFIG.PATH2KOPPEL_WEBIS))['train'].to_pandas()

In [4]:
ds_koppel

                   author                                               text
0     Henry_David_Thoreau  a week on the concord and merrimack rivers. [p...
1     Henry_David_Thoreau  walden, and on the duty of civil disobedience ...
2             Oscar_Wilde  a woman of no importance a play by oscar wilde...
3             Oscar_Wilde  an ideal husband a play by oscar wilde * * * *...
4      Nathaniel_Hawtorne  introductory note. the house of the seven gabl...
5      Nathaniel_Hawtorne  preface a preface generally begins with a trui...
6   James_Fenimore_Cooper  chapter i "mine ear is open, and my heart prep...
7   James_Fenimore_Cooper  james fenimore cooper "i believe i could write...
8   James_Fenimore_Cooper  the water-witch; or, the skimmer of the seas. ...
9        Charlotte_Bronte  preface. this little book was written before e...
10       Charlotte_Bronte  preface a preface to the first edition of "jan...
11           Bernard_Shaw  misalliance _johnny tarleton, an ordinary youn...
12           Bernard_Shaw  preface to pygmalion. a professor of phonetics...
13           Bernard_Shaw  preface to getting married the revolt against ...
14    Ralph_Waldo_Emerson  the conduct of life. by r. w. emerson. boston:...
15    Ralph_Waldo_Emerson  english traits. by ralph waldo emerson. new an...
16            Anne_Bronte  introduction anne bront serves a twofold purpo...
17            Anne_Bronte  chapter i the parsonage all true histories con...
18        Herman_Melville  etymology. (supplied by a late consumptive ush...
19        Herman_Melville  i. how wellingborough redburn's taste for the ...